base = float(input("Digite a base: "))
altura = float(input("Digite a altura: "))
area = (base*altura) 
perimetro = 2*(base+altura)
print("O retangulo tem perimetro",perimetro,"com",area,"de area.")
